# Generated by Django 5.1.3 on 2025-08-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_reposteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
